grafana:
  enabled: true
  adminPassword: "1234"
  grafana.ini:
    "server":
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
  service:
    type: ClusterIP
  adminPassword: "1234"
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: ClusterIP

nodeExporter:
  enabled: true
