# Grafana를 monitoring-ingress 네임 스페이스로 끌어옴
apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy-svc
  namespace: monitoring-ingress
spec:
  type: ExternalName
  externalName: prometheus-stack-grafana.monitoring.svc.cluster.local



---
# ArgoCD를 monitoring-ingress 네임 스페이스로 끌어옴
apiVersion: v1
kind: Service
metadata:
  name: argocd-proxy-svc
  namespace: monitoring-ingress
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-tools-ingress
  namespace: monitoring-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.100.0.1/32"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-proxy-svc
            port:
              number: 80
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: argocd-proxy-svc
            port:
              number: 80
